### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by frenzymadness**
This new pull request is based on the initial effort to make this library Python 3 compatible in PR #6 .

Tests work with a local instance of Danted Socks5 proxy with both Python 2.7 and 3.

Anyone who can test it or provide settings for more testing scenarios, please do.

### CODE REVIEW

**Comment by BjarniRunar** [comment]
Cool! Thanks for doing this. I will test it (and probably merge) as soon as I can.

**Comment by lzap** [comment]
Thanks guys for doing this. When you merge this @BjarniRunar can I ask for a quick release (or some pre-release at least) so I can bump package in Fedora to be Python3 only?

**Comment by frenzymadness** [comment]
Can we please merge this PR and issue a new release?

**Comment by BjarniRunar** [comment]
To be honest, no, this isn't just getting merged until I have time to focus on it.

I have to clean it up because you didn't actually care about the backwards compatibility and just threw something together that works for you. Maybe dropping backwards compatibility is the right thing to do, but then leaving all that legacy python 2.x (for x << 7) code in there is really sloppy.

Either way, doing this properly is work and I have to find time to do it.

**Comment by frenzymadness** [comment]
I completely understand your approach but I cannot do more to test it because I am not a regular user of this tool. Moreover, I tried to keep backward compatibility as much as I can (that's the reason for six module here). Could you please tell me where I'm breaking compatibility with Python 2.7 and/or provide more tests so I can enhance my patch?

**Comment by BjarniRunar** [comment]
I've merged this. Thanks everyone for the contributions!

My pushback wasn't that there was lots of work necessary, it was that I needed time to focus so I actually understood what is going on. Reading it I immediately saw some issues and when that's the case it's natural to assume there are more. There were, but they were all minor, so that's great.

Sorry I didn't answer your question, but figuring out the answer was the exact same amount of work as just fixing it.

**Comment by frenzymadness** [comment]
Thank you!

**Comment by BjarniRunar** [comment]
Just a heads' up to @lzap and other interested parties - I do not consider this work quite finished yet. Please track #8 if you want to be notified when I think this is actually all working!

There will also be a new release tagged, 2.1.0.

**Comment by lzap** [comment]
Thank you very much for the heads up - keep me informed and once everything is released I will put the package back immediately.

**Pull request merged**
