### PR TITLE
Add support for python3

### PR DESCRIPTION
**Pull request by SunilMohanAdapa**
- Use print as function by importing from future.

- Use six wrapper library to support urllib functions on Python 2 and Python 3.

Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>

### CODE REVIEW

**Comment by frenzymadness** [comment]
Changes look good to me. Do you have a fully working setup? I'd like to help with porting but the tests do not work for me either with Python 2 nor 3.

**Comment by SunilMohanAdapa** [comment]
Setup:
```bash
apt install danted
cat << EOF > /etc/danted.conf
logoutput: syslog
internal: 127.0.0.1 port = 1080
external: wlp1s0
socksmethod: none
clientmethod: none
user.privileged: proxy
user.unprivileged: nobody
user.libwrap: nobody
socks pass {
 from: 127.0.0.1/24 to: 0.0.0.0/0
 log: connect error
}
client pass {
 from: 127.0.0.1/24 to: 0.0.0.0/0
 log: connect error
}
EOF
systemctl restart danted
```
Modify test.py to use SOCK5 proxy localhost on port 1080
```bash
./test.py
python3 ./test.py
```
Success output for python2:
```
Routes are: {'*': [(2, 'localhost', 1080, True, None, None, None)]}
*** Connect: ('66.171.248.178', 80) / None
*** Chain: [(2, 'localhost', 1080, True, None, None, None), [0, 'bot.whatismyipaddress.com', 80]]
*** Connect: localhost:1080
*** SOCKS5: ('bot.whatismyipaddress.com', 80)
*** Connected! (None)
1.2.3.4 <actually my IP>
*** Connect: ('127.0.0.1', 1234) / None
*** Chain: [(2, 'localhost', 1080, True, None, None, None), [0, '127.0.0.1', 1234]]
*** Connect: localhost:1080
*** SOCKS5: ('127.0.0.1', 1234)
*** Connected! (None)

```
Running using this I discovered that there are couple of things that need fixing at least:

```patch
-                req = req + (chr(0x03).encode() +
-                             chr(len(destaddr)).encode() + destaddr)
+                req = req + (chr(0x03).encode() + chr(len(destaddr)).encode() +
+                             destaddr.encode())
```
and also reimplement the overridden methods of socksockets at least makefile(). I am current short on time to take care of this.

**Comment by SunilMohanAdapa** [comment]
@frenzymadness , this is most important part of this effort. Please go ahead and raise another pull request. I will close this one.

**Comment by frenzymadness** [comment]
See #7

**Comment by SunilMohanAdapa** [comment]
#7 supersedes this merge request. Closing this one.

**Pull request closed without merging**
